[package]
name = "passer"
version = "0.1.0"
authors = ["Marcelo Lima <marcelowind@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aes-gcm = "0.6"
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
