[package]
name = "passer_wasm"
version = "0.7.3"
authors = ["Marcelo Lima <marcelowind@gmail.com>"]
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.22"
chacha20poly1305 = "0.10.1"
# Must match what aes-gcm-siv brings in
getrandom = { version = "*", features = ["js"] }
miniz_oxide = "0.9.0"
wasm-bindgen = "0.2.108"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
js-sys = "0.3.85"
