name: Check

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  server:
    name: Check Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --manifest-path server/Cargo.toml --all -- --check
      - name: Install cargo-hack
        run: cargo install cargo-hack
      - name: Check main
        run: cargo hack --feature-powerset check --manifest-path server/Cargo.toml --verbose --workspace
      - name: Check tests
        run: cargo hack --feature-powerset check --manifest-path server/Cargo.toml --verbose --workspace --tests
      - name: Check examples
        run: cargo hack --feature-powerset check --manifest-path server/Cargo.toml --verbose --workspace --examples
      - name: Lint main
        run: cargo hack --feature-powerset clippy --manifest-path server/Cargo.toml --verbose --workspace -- -W clippy::pedantic
      - name: Lint tests
        run: cargo hack --feature-powerset clippy --manifest-path server/Cargo.toml --verbose --workspace --tests -- -W clippy::pedantic
      - name: Lint examples
        run: cargo hack --feature-powerset clippy --manifest-path server/Cargo.toml --verbose --workspace --examples -- -W clippy::pedantic
      - name: Test
        run: cargo hack --feature-powerset test --manifest-path server/Cargo.toml --verbose --workspace --no-fail-fast
  wasm:
    name: Check Wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --manifest-path web/wasm/Cargo.toml --all -- --check
      - name: Install cargo-hack
        run: cargo install cargo-hack
      - name: Check main
        run: cargo hack --feature-powerset check --manifest-path web/wasm/Cargo.toml --verbose --workspace
      - name: Check tests
        run: cargo hack --feature-powerset check --manifest-path web/wasm/Cargo.toml --verbose --workspace --tests
      - name: Check examples
        run: cargo hack --feature-powerset check --manifest-path web/wasm/Cargo.toml --verbose --workspace --examples
      - name: Lint main
        run: cargo hack --feature-powerset clippy --manifest-path web/wasm/Cargo.toml --verbose --workspace -- -W clippy::pedantic
      - name: Lint tests
        run: cargo hack --feature-powerset clippy --manifest-path web/wasm/Cargo.toml --verbose --workspace --tests -- -W clippy::pedantic
      - name: Lint examples
        run: cargo hack --feature-powerset clippy --manifest-path web/wasm/Cargo.toml --verbose --workspace --examples -- -W clippy::pedantic
      - name: Test
        run: cargo hack --feature-powerset test --manifest-path web/wasm/Cargo.toml --verbose --workspace --no-fail-fast
